version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./db_data/sql_app.db
        target: /app/sql_app.db
        bind:
          create_host_path: true
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend